### ISSUE TITLE
Compile error on Cocoon.io

### ISSUE THREAD

**Issue by AndreasReitberger** [GameAnalytics/GA-SDK-CORDOVA#1]
Hi,
when I use the cordova plugin on cocoon.io I get following build error:

> COMPILER ERROR: 
> 
> /workspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/workspace/platforms/android/cordova-plugin-crosswalk-webview/ga-xwalk.gradle' line: 161
> 
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > Could not find method implementation() for arguments [org.xwalk:xwalk_core_library:23+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> CORDOVA LOG: 
> 
> [36m20180824T091409 [DEBUG] AndroidBuilder -[39m [prepare] cordova restore platforms
> [36m20180824T091409 [DEBUG] AndroidBuilder -[39m [prepare] adding engine android@6.2.3
> Subproject Path: CordovaLib
> Subproject Path: CordovaLib
> Subproject Path: CordovaLib
> Subproject Path: CordovaLib
> Subproject Path: CordovaLib
> Subproject Path: CordovaLib
> [36m20180824T091445 [DEBUG] AndroidBuilder -[39m [prepare] cordova restore plugins
> [36m20180824T091445 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.canvasplus.android@2.3.8
> [36m20180824T091445 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.canvasplus.ios@2.3.8
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.defaultres.android@1.0.1
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.devapp.android@1.5.3
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.splash.android@1.1.0
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin com.ludei.webviewplus.android@2.2.1
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-plugin-device@*
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-plugin-dialogs@*
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-plugin-gameanalytics@*
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-plugin-inappbrowser@*
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [prepare] adding plugin cordova-plugin-whitelist@1
> [36m20180824T091446 [DEBUG] AndroidBuilder -[39m [build]
> Warning: File /.android/repositories.cfg could not be loaded.
> [36m20180824T091447 [DEBUG] AndroidBuilder -[39m [build] create certs folder
> [36m20180824T091447 [DEBUG] AndroidBuilder -[39m [build] keystore
> [36m20180824T091448 [DEBUG] AndroidBuilder -[39m [build] create build.json
> [36m20180824T091448 [DEBUG] AndroidBuilder -[39m [build] call cordova
> Removed LAUNCHER flag
> ANDROID_HOME=/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux
> JAVA_HOME=/usr/lib/jvm/default-java
> Subproject Path: CordovaLib
> null
> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
> 	at build_9d2trztayc98mx0p6c4px57m9.run(/workspace/platforms/android/build.gradle:142)
> org.xwalk:xwalk_core_library:23+
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/workspace/platforms/android/cordova-plugin-crosswalk-webview/ga-xwalk.gradle' line: 161
> 
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > Could not find method implementation() for arguments [org.xwalk:xwalk_core_library:23+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1.045 secs
> [91m20180824T091452 [ERROR] AndroidBuilder -[39m { Error: /workspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/workspace/platforms/android/cordova-plugin-crosswalk-webview/ga-xwalk.gradle' line: 161
> 
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > Could not find method implementation() for arguments [org.xwalk:xwalk_core_library:23+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>     at ChildProcess.whenDone (/workspace/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:961:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
>   stderr:
>    '\nFAILURE: Build failed with an exception.\n\n* Where:\nScript \'/workspace/platforms/android/cordova-plugin-crosswalk-webview/ga-xwalk.gradle\' line: 161\n\n* What went wrong:\nA problem occurred evaluating root project \'android\'.\n> Could not find method implementation() for arguments [org.xwalk:xwalk_core_library:23+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\n',
>   stdout:
>    'null\nThe Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.\n\tat build_9d2trztayc98mx0p6c4px57m9.run(/workspace/platforms/android/build.gradle:142)\norg.xwalk:xwalk_core_library:23+\n\nBUILD FAILED\n\nTotal time: 1.045 secs\n',
>   code: 1 }

I only added the game analytics plugin and the "device" plugin to the project. The framework I'm using is Construct 3 if it matters.

Thank you!

**Comment by QuasarX** [comment]
I have same error.
I think it is not work with **Cocoon's Googleplay plugin**.
> cocoon-plugin-social-android-googleplaygames

If I remove this **'cocoon-plugin-social-android-googleplaygames'** in project. It is compiling with **GA plugin and Device plugin.**

I'm getting this error (You can see full log in Log.txt)

> Note: /workspace/platforms/android/src/com/ludei/googleplaygames/GPGService.java uses unchecked or unsafe operations.

[Log.txt](https://github.com/GameAnalytics/GA-SDK-CORDOVA/files/2321549/Log.txt)

**Used Cocoon version: 2.1.0
Apache Cordova android v6.2.3**

**Comment by the1schwartz** [comment]
The error: 

"Could not find method implementation() for arguments [org.xwalk:xwalk_core_library:23+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."

only happens with "Webview+" it should work for Android for "Webview" and "Canvas+".

Regarding the 'cocoon-plugin-social-android-googleplaygames' issue it looks like 'cocoon-plugin-social-android-googleplaygames' uses a very old version of google play services (9.0.2) so the plugin developer needs to update to the latest version (or ideal using '+' as version instead in the plugin.xml file) this should most likely solve the issue.

**Comment by AndreasReitberger** [comment]
Yes it does work with Canvas+ and WebView, however the game crashes on startup when the Cordova-GA plugin is installed. I did not add any further plugins (expected the "Device" plugin).
Can you provide a capx / c3p example which is working for you`?
I haven't got it working in Construct 2 / Construct 3. Either the built fails, or the game crashes on startup.

Thanks a lot!

**Comment by the1schwartz** [comment]
Here is a link to the c3p I used to test with:
https://drive.google.com/file/d/11D_rQ7f3aoQegBx59AM386ARB1vwLL_a/view?usp=sharing

**Comment by the1schwartz** [comment]
Followed this guide to export for Cocoon: 
https://shatter-box.com/knowledgebase/build-construct-3-games-cocoon/

**Comment by QuasarX** [comment]
@the1schwartz 
I'm getting this error. Project closing.

> Event sheet 1, event 3, action 2: Invalid expression: 'getConfigurationsContentAsString' is not an expression in 'GameAnalytics'

in **C3 r114** and using **GameAnalytics 1.1.3 Plugin**

And I can't get Expressions. Other plugins works on Expressions panel. GameAnalytics only loading..
![image](https://user-images.githubusercontent.com/13033837/44791669-d324e280-abaa-11e8-8720-21c527738ac9.png)

**Comment by the1schwartz** [comment]
Sorry forgot to release the latest version of the Construct SDK (2.0.0). Should be available now.

**Comment by QuasarX** [comment]
I tired install GA 2.0.0 on Firefox 61. 
Contruct 3 can't open. It is stuck "Loading Addons %99.."

I tired install GA 2.0.0 on Chrome 68.
Construct 3 openning but still same error. Expressions panel "Loading..."

**Comment by the1schwartz** [comment]
Ok. Should be fixed in v2.0.1 now

**Comment by AndreasReitberger** [comment]
Still crashing on my end.
I just added the GA plugin to construct and call the "Initilize SDK" on startup.

Cocoon Version: latest (2.3.0)
Engine: Canvas+

This is my config.xml

```
<?xml version="1.0" encoding="utf-8"?>
	<widget xmlns="http://www.w3.org/ns/widgets" xmlns:cocoon="http://cocoon.io/ns/1.0" xmlns:cdv="http://cordova.apache.org/ns/1.0" id="com.shatterbox.ga" version="1.0.0">
		<name>Game Analytics (C3)</name>
		<description>A sample Cocoon application that responds to the deviceready event.</description>
		<author email="andy.reitberger@gmail.com" href="https://shatter-box.com">Andreas Reitberger </author>
		<content src="index.html"/>
		<plugin name="cordova-plugin-whitelist" version="1"/>
		<access origin="*"/>
		<allow-intent href="http://*/*"/>
		<allow-intent href="https://*/*"/>
		<allow-intent href="tel:*"/>
		<allow-intent href="sms:*"/>
		<allow-intent href="mailto:*"/>
		<allow-intent href="geo:*"/>
		<platform name="android">
			<allow-intent href="market:*"/>
			<preference name="enabled" value="true"/>
		</platform>
		<platform name="ios">
			<allow-intent href="itms:*"/>
			<allow-intent href="itms-apps:*"/>
		</platform>
		<preference name="Orientation" value="portrait"/>
		<preference name="Fullscreen" value="true"/>
		<plugin name="cordova-plugin-device" spec="*"/>
		<plugin name="cordova-plugin-dialogs" spec="*"/>
		<plugin name="cordova-plugin-inappbrowser" spec="*"/>
		<plugin name="com.ludei.canvasplus.ios" spec="*"/>
		<plugin name="com.ludei.canvasplus.android" spec="*"/>
		<plugin name="cordova-plugin-gameanalytics" spec="*"/>
	</widget>
```
Here is the c3p project.
https://drive.google.com/open?id=1b1fWl01O8VCP2h-0guivUALI1Q0g8wrI

What do I miss?

**Comment by the1schwartz** [comment]
It seems to work using Webview but not using Canvas+, I will try to look into it

**Comment by the1schwartz** [comment]
I just get a black screen when building using Canvas+ even if I just export a simple project with just a text with "Hello world" on the on screen. I am not sure if I am doing something wrong.

**Comment by AndreasReitberger** [comment]
What Cocoon version are you using? I'm using "Latest", should be 2.3.0.

![image](https://user-images.githubusercontent.com/2952443/44867089-35ebac00-ac87-11e8-98da-bb076ab83b54.png)

There is a "3.0.0-beta" using the latest cordova version, but it's not stable yet.
I'm not sure, if the crash is because of the game analytics plugin or caused by the compiler itself.

Thanks for looking into it!

**Comment by the1schwartz** [comment]
Yes I am using "latest" as shown in the screenshot as well

**Comment by QuasarX** [comment]
This should be closed. Cocoon.io shotdown
